defaults:
  - data: data
  - module/optimizer: adamw
  - module/model: proteoscope
  - trainer: cuda

hydra:
  run:
    dir: /home/ec2-user/outputs-proteoscope/proteoscope/${now:%Y-%m-%d}/${now:%H-%M-%S}

model_type: proteoscope #cytoself proteoscope autoencoder
chkpt: null #/home/ec2-user/outputs-proteoscope/autoencoder/2023-08-15/03-57-15/checkpoints/last.ckpt # null
module:
  image_variance: 0.0167
  dropout: 0.2
  image_height: 96
  num_class: 1049