model_type: proteoscope #cytoself proteoscope autoencoder

defaults:
  - _self_
  - data: data
  - module/optimizer: adamw
  - trainer: cuda
  - module/model: proteoscope
  - splits: standard # all_proteins, standard, train_proteins

hydra:
  run:
    dir: /home/ec2-user/outputs/proteoscope/${now:%Y-%m-%d}/${now:%H-%M-%S}

chkpt: /home/ec2-user/outputs/proteoscope/2023-09-07/18-26-19/checkpoints/last.ckpt #last.ckpt # null
module:
  dropout: 0.2
  image_height: 100