model_type: proteoscope #cytoself proteoscope autoencoder proteoloc

defaults:
  - _self_
  - data: data # data  data-loc data-loc-esm
  - module/optimizer: adamw
  - trainer: cuda # cuda  cuda-loc  cuda-loc-esm
  - module/model: proteoscope # proteoloc-esm
  - splits: standard # all_proteins, standard, train_proteins

hydra:
  run:
    dir: /home/ec2-user/outputs/proteoscope/${now:%Y-%m-%d}/${now:%H-%M-%S}

chkpt: null #/home/ec2-user/outputs/proteoscope/2023-09-05/04-00-01/checkpoints/last.ckpt #last.ckpt # null
reset: False # True/ False
module:
  dropout: 0.2
  image_height: 100