defaults:
  - data: data
  - module/optimizer: adamw
  - module/model: proteoscope
  - trainer: cuda

hydra:
  run:
    dir: /home/ec2-user/outputs-proteoscope/${now:%Y-%m-%d}/${now:%H-%M-%S}

model_type: proteoscope
chkpt: /home/ec2-user/outputs-proteoscope/2023-07-21/04-22-30/checkpoints/last.ckpt # null
module:
  unet_number: 1