defaults:
  - data: data
  - module/optimizer: adamw
  - module/model: proteoscope
  - trainer: cuda

hydra:
  run:
    dir: /home/ec2-user/outputs-proteoscope/${now:%Y-%m-%d}/${now:%H-%M-%S}

chkpt: /home/ec2-user/outputs-proteoscope/2023-05-30/21-53-37/checkpoints/last.ckpt # null
module:
  unet_number: 2