model_type: proteoloc #cytoself proteoscope autoencoder proteoloc

defaults:
  - _self_
  - data: data-loc # data 
  - module/optimizer: adamw
  - trainer: cuda-loc # cuda
  - module/model: proteoloc
  - splits: standard # all_proteins, standard, train_proteins

hydra:
  run:
    dir: /home/ec2-user/outputs/proteoloc/${now:%Y-%m-%d}/${now:%H-%M-%S}

chkpt: null #/home/ec2-user/outputs/proteoscope/2023-09-05/04-00-01/checkpoints/last.ckpt #last.ckpt # null
reset: False # True/ False
module:
  dropout: 0.2
  image_height: 100