defaults:
  - data: data
  - module/optimizer: adamw
  - module/model: cytoself
  - trainer: cuda

hydra:
  run:
    dir: /home/ec2-user/outputs-proteoscope/cytoself/${now:%Y-%m-%d}/${now:%H-%M-%S}

model_type: cytoself #cytoself proteoscope
chkpt: /home/ec2-user/outputs-proteoscope/cytoself/2023-08-09/23-37-06/checkpoints/last.ckpt # null
module:
  unet_number: 1