model_type: proteoclip #cytoself proteoscope autoencoder proteoloc proteoclip proteocytoclass

defaults:
  - _self_
  - data: data # data data-proteoloc data-proteoloc-lora data-proteoscope-lora data-proteoscope-esm
  - module/optimizer: adamw-proteoclip
  - trainer:  cuda-proteoclip # cuda  cuda-proteoloc  cuda-proteoloc-lora cuda-proteoscope-lora
  - module/model: proteoclip # proteoloc-lora proteoscope-lora
  - splits: standard # all_proteins, standard, train_proteins for cytoself use all_proteins

hydra:
  run:
    dir: /home/ec2-user/outputs/proteoclip/${now:%Y-%m-%d}/${now:%H-%M-%S}

chkpt: null #/home/ec2-user/outputs/proteoscope/2023-09-15/06-06-05/checkpoints/last.ckpt #last.ckpt # null
reset: False # True/ False
# chkpt: /home/ec2-user/outputs/proteoscope/2023-09-05/05-49-46/checkpoints/last.ckpt #last.ckpt # null
# reset: True # True/ False