model_type: cytoself #cytoself proteoscope autoencoder

defaults:
  - _self_
  - data: data
  - module/optimizer: adamw
  - trainer: cuda
  - module/model: cytoself
  - splits: all_proteins

hydra:
  run:
    dir: /home/ec2-user/outputs/cytoself/${now:%Y-%m-%d}/${now:%H-%M-%S}

chkpt: null # /home/ec2-user/outputs/proteoscope/2023-08-20/20-54-36/checkpoints/last.ckpt # null
module:
  dropout: 0.2
  image_height: 100