defaults:
  - data: data
  - module/optimizer: adamw
  - module/model: cytoself
  - trainer: cuda

hydra:
  run:
    dir: /home/ec2-user/outputs-proteoscope/${now:%Y-%m-%d}/${now:%H-%M-%S}

chkpt: null # /home/ec2-user/outputs-proteoscope/2023-07-10/19-49-35/checkpoints/last.ckpt # null
module:
  unet_number: 2