device: cuda
num_devices: 1 #8
gradient_clip_val: null
precision: 16-mixed # 16
val_check_interval: 600 # 1000
limit_val_batches: 50 # 20
log_every_n_steps: 10 # 50
batch_size: 32
num_workers: 16
accumulate: 1
max_steps: 240_000