learning_rate: 2e-4 # 1e-4
learning_rate_min_factor: 0.1
beta_1: 0.9
beta_2: 0.98
eps: 0.00000001 # 1e-8
weight_decay: 0.01
warmup: 1 # in steps, 2869 steps / epoch if batch size 4 * 4 * 64
max_iters: 600_000 # 60_000 ~ steps for 10 epochs - always do 2 x expectected for cosine